
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth'
import { authOptions } from "@/lib/authOptions";
import { connectDB } from "@/dbConnection/ConnectDB";
import Student from "@/models/Student.model";
import SessionWrapper from "./SessionWrapper";
import { YearProvider } from "@/components/YearProvider";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IIT Indore Time Table Manager",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB()
  const session = await getServerSession(authOptions)
  
  let year = null
  if (session?.user?.id) {
    const student = await Student.findOne({ userId: session.user.id })
    year = student?.year || null
  }
  console.log("2nd",year)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <SessionWrapper>
      <Suspense fallback={<div>Loading...</div>}>
          <YearProvider year={year}>
            {children}
          </YearProvider>
      </Suspense>
        </SessionWrapper>
      </body>
    </html>
  );
}
